[project]
name = "TidalTime"
version = "1.0.0"
description = "Scrape UK tidal records from BBC.co.uk"
authors = [{ name = "Wei Liu", email = "newway.lw@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.3",
    "beautifulsoup4>=4.11.1",
    "aiohttp>=3.9.0",
    "lxml>=4.9.0",
    "tenacity>=8.0.1",
    "pyserde>=0.12.2",
    "typing-extensions>=4.8.0",
    "tqdm>=4.64.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tidal"]
